//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movie()
        {
            this.tickets = new HashSet<ticket>();
        }
    
        public string ID { get; set; }
        public string name { get; set; }
        public string releaseDate { get; set; }
        public Nullable<decimal> price { get; set; }
        public string des { get; set; }
        public string imgMovie { get; set; }
        public string mIdAdress { get; set; }
        public string mIdCinemar { get; set; }
    
        public virtual address address { get; set; }
        public virtual cinemar cinemar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> tickets { get; set; }
    }
}
