//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string IDaddress { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public string IDMovie { get; set; }
        public string IDCinemar { get; set; }
        public Nullable<int> IDOrder { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual address address { get; set; }
        public virtual cinemar cinemar { get; set; }
        public virtual movie movie { get; set; }
        public virtual Order Order { get; set; }
    }
}
